name: CI

on:
  push:
    branches: [ testing-master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ testing-master ]

permissions:
  packages: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    services:
      registry:
        image: registry:2
        ports:
        - 5000:5000

    steps:
    - name: Free up disk space
      run: |
        set -x

        # Delete unnecessary files to free up space
        df -h
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "/usr/local/lib/android"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h

    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate local metadata for CI image
      id: meta_ci
      uses: docker/metadata-action@v3
      with:
        images: |
          localhost:5000/zephyrproject-rtos/ci-testing

    - name: Generate local metadata for Developer image
      id: meta_developer
      uses: docker/metadata-action@v3
      with:
        images: |
          localhost:5000/zephyrproject-rtos/zephyr-build-testing

    - name: Generate push metadata for CI image
      if: ${{ github.event_name != 'pull_request' }}
      id: meta_ci_push
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/zephyrproject-rtos/ci-testing

    - name: Generate push metadata for Developer image
      if: ${{ github.event_name != 'pull_request' }}
      id: meta_developer_push
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/zephyrproject-rtos/zephyr-build-testing

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host

    - name: Build CI docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta_ci.outputs.tags }}
        labels: ${{ steps.meta_ci.outputs.labels }}

    - name: Build Developer docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.user
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta_developer.outputs.tags }}
        labels: ${{ steps.meta_developer.outputs.labels }}
        build-args: |
          BASE_IMAGE=localhost:5000/zephyrproject-rtos/ci-testing:${{ steps.meta_ci.outputs.version }}

    - name: Login to GitHub Container Registry
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push CI docker image
      if: ${{ github.event_name != 'pull_request' }}
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: localhost:5000/zephyrproject-rtos/ci-testing:${{ steps.meta_ci.outputs.version }}
        dst: ${{ steps.meta_ci_push.outputs.tags }}

    - name: Push Developer docker image
      if: ${{ github.event_name != 'pull_request' }}
      uses: akhilerm/tag-push-action@v2.0.0
      with:
        src: localhost:5000/zephyrproject-rtos/zephyr-build-testing:${{ steps.meta_developer.outputs.version }}
        dst: ${{ steps.meta_developer_push.outputs.tags }}
